### PR TITLE
openwisp-controller-setup-task

### PR DESCRIPTION
**Pull request by xamfy**
Create task to setup openwisp-controller

### CODE REVIEW

**Comment by xamfy** [comment]
@rohithasrk can you suggest?

**Comment by rohithasrk** [comment]
Tags could be blog, community, research etc.
Categories could be Research, Installation. Coding doesn't seem really relevant. What do you think?

**Comment by xamfy** [comment]
@rohithasrk Yes, coding is not relevant, the tags you suggest are appropritate.

**Comment by xamfy** [comment]
@rohithasrk since the last date is 24th, should I just write the detailed tasks from the list you gave and send a pull request, than you and @nemesisdesign can suggest the changes

**Comment by xamfy** [comment]
@rohithasrk Done

**Pull request merged**
